### ISSUE TITLE
Show just first ten related items

### ISSUE THREAD

**Issue by gsf** [wavefarm/admin#30]
When displaying related items, show first ten with "show more" (or "show all"?) button below.

**Comment by gsf** [comment]
One way to address this would be to contain related items in a div with a max-height and overflow:auto.

**Comment by galenjosephhunter** [comment]
This is a high-priority item. Currently it is extremely difficult to search for a specific item in admin because there is no way to sort results by date and there is no way to see more than the first ten results, which is basically a wall against being able to locate a specific record if the keywords in the "name" are not unique.

**Comment by galenjosephhunter** [comment]
Fixed with infinite scroll!

**Comment by gsf** [comment]
This is separate from infinite scroll -- it's the display of related items on the item form. I'm thinking I can fix it with a max-height div and overflow: auto.

**Comment by galenjosephhunter** [comment]
oh ok.
